services:
    rooksake-front:
       image: igrowker/i004-rooksafe-front
       restart: unless-stopped
       build:
         context: .
         dockerfile: Dockerfile
       working_dir: /usr/share/nginx/html
       networks:
         - rooksafe
       ports:
         - "8080:80"
       volumes:
         - ./public:/usr/share/html/public
         - "/etc/timezone:/etc/timezone:ro"
         - "/etc/localtime:/etc/localtime:ro"

networks:
  rooksafe:
    name: rooksafe
    external: true
